# Generated by Django 4.0.8 on 2022-10-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=1024)),
                ('interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.IntegerField()),
                ('response_status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitors.monitor')),
            ],
        ),
    ]
